services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    # container_name: namakemono_back
    ports:
      - '3000:3000'
    working_dir: /app
    networks:
      - my-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    # container_name: namakemono_front
    ports:
      - '8080:8080'
    depends_on:
      - back
    working_dir: /app/vue-project
    networks:
      - my-network

  proxy:
    image: httpd:2.4
    # container_name: proxy_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/apache_conf/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./proxy/apache_conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./proxy/apache_conf/certs:/usr/local/apache2/conf/certs
    depends_on:
      - front
      - back
    networks:
      - my-network

  selenium:
    image: selenium/standalone-chromium:latest
    # container_name: namakemono_selenium
    depends_on:
      - front
    ports:
      - "4444:4444"
    networks:
      - my-network
  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    # container_name: namakemono_tests
    depends_on:
      - front
      - back
      - selenium
    networks:
      - my-network

  db:
    image: postgres
    # container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    depends_on:
      - back
    networks:
      - my-network

# networks:
#   my-network:
    #  external: true
