name: Run Selenium Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Firebase credentials file
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" | base64 --decode > back/app/vue-project-ee823-firebase-adminsdk-lhbyv-d0398de819.json
            
      - name: Build and run services
        run: |
          # ネットワークが存在しない場合に作成
          docker network create my-network || true
          # テストコンテナをビルドする
          docker compose build tests
          # テストコンテナを実行してテストを走らせる
          docker compose run --rm tests
